// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTeeShapePanel;

/////////////////////////////////////////////////////////////////////////////
// CAnnotationTool wrapper class

class CAnnotationTool : public COleDispatchDriver
{
public:
	CAnnotationTool() {}		// Calls COleDispatchDriver default constructor
	CAnnotationTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAnnotationTool(const CAnnotationTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetPosition();
	void SetPosition(long nNewValue);
	CTeeShapePanel GetShape();
	CString GetText();
	void SetText(LPCTSTR lpszNewValue);
};
