// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CPen1;

/////////////////////////////////////////////////////////////////////////////
// CCursorTool wrapper class

class CCursorTool : public COleDispatchDriver
{
public:
	CCursorTool() {}		// Calls COleDispatchDriver default constructor
	CCursorTool(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCursorTool(const CCursorTool& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	VARIANT GetSeries();
	void SetSeries(const VARIANT& newValue);
	BOOL GetFollowMouse();
	void SetFollowMouse(BOOL bNewValue);
	CPen1 GetPen();
	BOOL GetSnap();
	void SetSnap(BOOL bNewValue);
	long GetStyle();
	void SetStyle(long nNewValue);
	double GetXVal();
	void SetXVal(double newValue);
	double GetYVal();
	void SetYVal(double newValue);
};
