// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CTeeShadow wrapper class

class CTeeShadow : public COleDispatchDriver
{
public:
	CTeeShadow() {}		// Calls COleDispatchDriver default constructor
	CTeeShadow(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTeeShadow(const CTeeShadow& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:

// Operations
public:
	long GetHorizSize();
	void SetHorizSize(long nNewValue);
	long GetVertSize();
	void SetVertSize(long nNewValue);
	unsigned long GetColor();
	void SetColor(unsigned long newValue);
};
